# === GPU ===
hwdec=auto-copy
hwdec-codecs=all
vo=gpu
msg-level=all=error,ffmpeg=fatal

# === ОКНО ПО РАЗМЕРУ ВИДЕО ===
autofit-larger=90%x90%
autofit-smaller=30%x30%
keepaspect-window=no
geometry=50%:50%

# === SVP ===
input-ipc-server=/tmp/mpvsocket
hr-seek-framedrop=no

# === СИНХРОНИЗАЦИЯ ===
video-sync=audio
audio-buffer=0.2

# === ЗВУК ВЫКЛ ПО ДЕФОЛТУ ===
mute=yes

# === КЕШ ===
cache=yes
demuxer-max-bytes=512M

# === КАЧЕСТВО ===
scale=spline36
cscale=spline36
dscale=mitchell

# === ДЕБАНДИНГ ===
deband=no

# === HDR ===
tone-mapping=auto
target-colorspace-hint=yes

# === DITHERING ===
dither-depth=auto

# === АВТОПОВТОР ===
loop-file=inf

# === OSD ===
osd-font-size=32
osd-duration=2000

# === YT-DLP ===
ytdl-format=bestvideo[height<=1080]+bestaudio/best
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=cookies-from-browser=brave
